version: '3.8'

# This is how you persist data between container restarts
volumes:
  mongo_data:
  log_data:
  graylog_data:

# Define an overlay network for service discovery in Swarm
networks:
  graylog_network:
    driver: overlay

# For Docker Swarm deployments
configs:
  graylog_config:
    file: ./config/graylog/graylog.conf
services:
  # Graylog stores configuration in MongoDB
  mongo:
    image: mongo:6.0.5-jammy
    command: --wiredTigerCacheSizeGB 1
    volumes:
      - "mongo_data:/data/db"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2G
    networks:
      - graylog_network

  # The logs themselves are stored in Opensearch
  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=1Aw4rdConsulting"
    volumes:
      - "log_data:/usr/share/opensearch/data"
    deploy:
      restart_policy:
        condition: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200/tcp
    networks:
      - graylog_network

  graylog:
    image: graylog/graylog:6.1
    environment:
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "!Aw4rdConsulting"
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: "0fbf83ed3f8cf11cb36e293cc768c45760eb167fd09b3eb1f87507a3445c8f1b"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9001"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9001/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongo:27017/graylog"
      GRAYLOG_TIMEZONE: "America/Chicago"
      TZ: "America/Chicago"

    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
    volumes:
      - "graylog_data:/usr/share/graylog/data"
    configs:
      - source: graylog_config
        target: /usr/share/graylog/data/config/graylog.conf
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 9001:9001/tcp   # Graylog web interface and REST API
      - 1514:1514/udp   # Syslog - MVS
      - 1515:1515/udp   # Syslog - ISC
      - 1516:1516/udp   # Syslog - CFS
      - 1517:1517/udp   # Syslog - MRS / UMG
      - 1518:1518/udp   # Syslog - SAS
      - 1519:1519/udp   # Syslog - EAS
      - 1520:1520/udp   # Syslog - DCM
      - 1521:1521/udp   # Syslog - RTR
      - 1522:1522/udp   # Syslog - SWT
      - 2055:2055/udp   # Netflow
      - 12201:12201/tcp # GELF
      - 12201:12201/udp # GELF
    networks:
      - graylog_network